# Site settings
title: Jekyll-Docs
email: your-email@domain.com
description: "A Jekyll Theme dedicated to documentation"
baseurl: ""
url: "http://benignware.com"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty